name: CI

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: Screenly/edge-apps-actions/checks@v26.9.1
